[package]
name = "rust-nn-practice"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
ndarray = "0.16.1"
plotters = "0.3.7"
rand = "0.9.0"
rayon = "1.10.0"
tokio = { version = "1.45.0", features = ["full"] }

[profile.release]
debug = true
